//
// Created by hazyparker on 2021/11/26.
//

#ifndef NONLINEAR_OPTIMIZATION_LMMETHOD_H
#define NONLINEAR_OPTIMIZATION_LMMETHOD_H

void TrustRegionMethod();

#endif //NONLINEAR_OPTIMIZATION_LMMETHOD_H
